### ISSUE TITLE
Add a ‘6 months’ option to the Earnings section

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-info#107]
Now that Balanced has been live for a year, we can compare 6-month time periods, as well:

![5271BCE3-6102-4C6C-B5B8-CB4DCCDE45EB](https://user-images.githubusercontent.com/63842577/167313563-e6e44374-f0b1-4bfb-b989-09cfef01f70b.jpeg)

While we’re adjusting this page, let’s update the red used here to `#fb6a6a`:
![305731EC-40AA-4061-AF95-9D946D1B664E](https://user-images.githubusercontent.com/63842577/167313574-0626dc56-9d5f-4757-829c-4bb7e71dbf33.jpeg)

By the way, @BennyOptions is this expected? I can understand the $ value being less while the market is down, but why have the token amounts also dropped by a significant margin?

**Comment by BennyOptions** [comment]
@parrot9design mine looks different. Not sure why, but I confirmed the numbers I see are correct by checking the token holders of each token and looking at how much is in the DAO Fund.

Example:

BALN Holdings: https://tracker.icon.foundation/token/cxf61cd5a45dc9f91c15aa65831a30a90d59a09619#tokenholders
[cx835b300dcfe01f0bdb794e134a0c5628384f4367](https://tracker.icon.foundation/contract/cx835b300dcfe01f0bdb794e134a0c5628384f4367)

<img width="1202" alt="Screen Shot 2022-05-08 at 4 14 42 PM" src="https://user-images.githubusercontent.com/43685868/167314166-257f48a6-d5ac-477b-a05f-aca2b43fbf6b.png">

**Comment by parrot9design** [comment]
> @parrot9design mine looks different. Not sure why, but I confirmed the numbers I see are correct by checking the token holders of each token and looking at how much is in the DAO Fund.

Strange, now mine shows the same numbers you’re seeing. Not sure what happened there. 🤔
