### ISSUE TITLE
Add a Stability Fund section to the Performance Details page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-info#109]
If [this 24-hour proposal](https://app.balanced.network/vote/proposal/45) is approved, we’ll need to add a `Stability fund` section to the Performance Details page ASAP to show the current balance of stablecoins.

Mockup is here: http://balanced-development.s3-website-us-east-1.amazonaws.com/stats-dev/financial-statements/

Should only display the balances of bnUSD, IUSDC, and USDS

Related: https://github.com/balancednetwork/balanced-java-contracts/pull/102

**Comment by parrot9design** [comment]
Let's also add an entry for `Stability Fund fees` to the Earnings section:

![Screen Shot 2022-05-14 at 2 21 43 PM](https://user-images.githubusercontent.com/63842577/168407311-a1dd1925-daa5-4a36-98ef-8ab612e9f847.png)

**Comment by BennyOptions** [comment]
Refernce #110 for proper endpoints, they are somewhat redundant issues

**Comment by hetfly** [comment]
There is an issue created in backend repo to reflect Stability fund fees in DAO income. 
Rest is good to review.
