### ISSUE TITLE
Create an endpoint for the Stability fund

### ISSUE THREAD

**Issue by hetfly** [balancednetwork/balanced-network-info#110]
Related to https://github.com/balancednetwork/balanced-network-info/issues/109

We will need to query stability fund balances based on timestamp, it would be ideal to have it similar to DAO fund endpoint, see https://balanced.sudoblock.io/api/v1/docs#/stats/get_daofund_balance_sheet_api_v1_stats_daofund_balance_sheet_get

example timestamp ```1652252887000000 ```

**Comment by BennyOptions** [comment]
@hetfly this endpoint should help you. @robcxyz can answer questions if it's not clear from the docs. You enter a timestamp and it returns a blockheight closest to the timestamp. From there, the UI can ping the node for balanceOf (blockHeight) for different tokens and different contracts. We should migrate all single-point-in-time API usage to this model. It's a new feature supported by ICON Nodes that allows you to query state at a given block height

https://tracker.v2.mainnet.sng.vultr.icon.community/api/v1/docs/index.html#/Blocks/get_api_v1_blocks_timestamp__timestamp

**Comment by BennyOptions** [comment]
This should also help when calling the icon node once you have the blockHeight

https://www.icondev.io/icon-stack/client-apis/json-rpc-api/v3.

So to summarize, this can be used for single-point-in-time queries. For example, let's compare today's DAO Fund holdings to the holdings on May 1st.

Calling backend API:
- Call for blockheight today, return = x
- Call for blockheight for May 1st, return = y

Calling ICON Node API:
- balanceOf (DAOFund, blockheight = x)
- balanceOf (DAOFund, blockheight = y)
