### ISSUE TITLE
Display ICON network-owned liquidity

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#183]

**Comment by parrot9design** [comment]
Rather than add a whole new section for this, we could add these options to the Exchange section:

<img width="1030" alt="exchange-tabs" src="https://github.com/balancednetwork/balanced-network-info/assets/63842577/3ddd75c7-e053-4199-a91f-3f56aec7c116">

**Comment by hetfly** [comment]
@parrot9design what would the columns look like for Balanced and ICON Network options?

In the performance details, the POL is shown with its value only, plus the possibility to see the past values as well:
<img width="1164" alt="image" src="https://github.com/balancednetwork/balanced-network-info/assets/13098459/665894b1-51eb-4144-81f9-3e7204d9f122">

I can see the reasons for both putting it in the Performance details page as well as not. But based on the data showed in the Exchange columns, I'd lean towards showing the POL/NOL elsewhere and keep the Exchange section showing just the overall exchange data.

**Comment by parrot9design** [comment]
Dammit @hetfly, I was hoping for a quick win here. 😅

Thankfully saner minds prevailed. I'll go back to the drawing board. 😂
