### ISSUE TITLE
Display bnUSD global cap

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#184]

**Comment by parrot9design** [comment]
Is this related to https://github.com/balancednetwork/balanced-network-info/issues/185? 

If so, we could add it to the bnUSD metadata for each collateral type:
<img width="1238" alt="Screenshot 2024-02-27 at 4 13 51 PM" src="https://github.com/balancednetwork/balanced-network-info/assets/63842577/47557cd7-5d79-4fe4-9aad-71a430acac06">
