### ISSUE TITLE
DAO Performance Details

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#19]
I'd like a new section/page that focuses specifically on the performance of the DAO over time. We need to show how much value the DAO brings to BALN, and how much the DAO is earning. This is what I would like to show:

Fees - this can all be shown in one table. I'm thinking each row of the table will be 1 day, then at the top of the table we can show totals. We should also have a column for each asset type rather than converting to USD value in order to make it most accurate.

- Total fees earned all time (top of the table)
- Total origination fees earned all time (top of the table)
- Total trading fees earned all time (top of the table)
- Daily performance of the above categories

DAO Fund
- Current AUM of each asset type
- Chart showing the growth over time
- Number of staked BALN - static number
- Number of LPed BALN - static number
- Value backing each eligible BALN in terms of DAO Fund (DAO Fund size / total staked/LPed BALN)

**Comment by BennyOptions** [comment]
Building off my initial thoughts above, I'd like to essentially create an income statement and balance sheet for the DAO and allow users to select timeframes.

Income Statement:

- Total fees earned of each asset type (current dollar price of these assets)
- Total fees paid out to stakers
- Net Income (first bullet minus second bullet)

Balance Sheet (This is static at a given point in time. For example, Balance Sheet on Day 100)
- Assets held by the DAO of each type
- Value of 1,000 BALN based on DAO Fund holdings

**Comment by parrot9design** [comment]
The income statement and balance sheet are here: http://balanced-development.s3-website-us-east-1.amazonaws.com/stats-dev/financial-statements/, linked to from the governance section on the Stats page: http://balanced-development.s3-website-us-east-1.amazonaws.com/stats-dev/.

The income statement allows you to choose trailing time periods (1 day, 1 week, 1 month, and 3 months, as well as 6 months and 1 year when we get that far along).

The balance sheet shows the DAO fund balance on that day, and another day of your choice (default to the day prior), as well as the % change between them.

We still need to get both the time period and date picker in place, but the rest is ready to implement.

The data will come from Geometry’s backend APIs. Depending on how fast it is to pull through, we may need some animations similar to the Vote page.

@hetfly let us know if you have any questions about the implementation.

**Comment by BennyOptions** [comment]
Remove the following:

- Replace "Financial Statements" with "Performance Details"
- Replace "Income Statement" with "Earnings"
- Replace "Balance Sheet" with "Holdings"

**Comment by BennyOptions** [comment]
https://balanced.geometry.io/api/v1/docs#/stats/get_daofund_balance_sheet_api_v1_stats_daofund_balance_sheet_get

https://balanced.geometry.io/api/v1/docs#/stats/get_income_statement_api_v1_stats_income_statement_get

**Comment by parrot9design** [comment]
> Remove and replace the following:
> 
> * Replace "Financial Statements" with "Performance Details"
> * Replace "Income Statement" with "Earnings"
> * Replace "Balance Sheet" with "Holdings"

`Earnings` and `Holdings` are good, but let’s change the `Financial statements` heading and intro text to:

> ## Performance details
> Track Balanced's performance over time. All $ values are in USD, based on the current price of each asset.
