### ISSUE TITLE
Grab-bag of fixes for the Stats page

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-info#214]
- [x] Improve the decimal precision for BTC:
<img width="834" alt="Screenshot 2024-07-18 at 6 01 53 PM" src="https://github.com/user-attachments/assets/a12e7b52-c982-4467-8c20-f7c5438858b8">

----

- [x] Rename BTCB (make it `BTCB (old)` until we're ready to remove it entirely):
<img width="270" alt="Screenshot 2024-07-18 at 6 02 03 PM" src="https://github.com/user-attachments/assets/ab33b8fa-13c1-4b21-85ca-58c7bdf89833">

---

- [x] Fix the Staking APR for ICON collateral:
<img width="587" alt="Screenshot 2024-07-18 at 6 05 01 PM" src="https://github.com/user-attachments/assets/bad86833-1c25-4434-9f9e-f23d4206ed0e">

---

- [x] Update the Reserve Fund chart to display the full list of assets it holds and use the correct colour palette:
![Screenshot 2024-07-18 at 6 07 14 PM](https://github.com/user-attachments/assets/965f2b60-9184-46b2-aac7-d49e68573202)

---

- [x] Change `0xa.optimism` to `Optimism` in the USDC list on the Stats & performance details pages
<img width="340" alt="Screenshot 2024-07-18 at 6 08 07 PM" src="https://github.com/user-attachments/assets/70437398-8134-488e-8fa9-a70dd80dc778">

- [x] Change `0x89.polygon` to `Polygon` in the USDC list on the Stats & performance details pages

- [x] Also change `Archway USDC` to `USDC` in the Withdrawal Limits section

---

- [x] Make the withdraw limit percentages consistent - some are green while others are red, some have a space after the `~`, some don't.

<img width="400" alt="Screenshot 2024-07-18 at 6 10 38 PM" src="https://github.com/user-attachments/assets/465aac13-b2d8-4b8b-b20d-031eb52c6acd"> <img width="400" alt="Screenshot 2024-07-18 at 6 10 46 PM" src="https://github.com/user-attachments/assets/886fcc10-3c8b-49f0-82d8-84f0fb754c68"> <img width="400" alt="Screenshot 2024-07-18 at 6 10 52 PM" src="https://github.com/user-attachments/assets/02c3ec2d-53ce-46f1-b515-4db647e952c4">

---

- [x] Add a subtotal for `Distributions` in the Earnings section 
<img width="843" alt="Screenshot 2024-07-18 at 6 13 22 PM" src="https://github.com/user-attachments/assets/7c95060d-c02f-4702-bb08-7dce0afc2cec">

---

- [x] Update the BALN logo in the `Holdings` section (it's using the old version with the larger B)
![Screenshot 2024-07-18 at 6 15 02 PM](https://github.com/user-attachments/assets/caebbd7d-2b79-47a7-9313-47152a1cbb16)

---

- [x] Fix the enshrinement entry in the Earnings section so the tooltip always stays beside the label:
![Screenshot 2024-08-12 at 3 43 14 PM](https://github.com/user-attachments/assets/90ed323b-2f27-418e-9936-483b0e8167c9)

---

We'll also need to consider adding a time filter to the `ICX burned` section before the bars get too much thinner. 😅

**Comment by hetfly** [comment]
@parrot9design I've added some new colours for the network owned liquidity chart since we're out of the brand ones. Can't decide which ones to include, I would appreciate your input here 😅 

https://balanced-network-stats-phromduw1-balanced-dao.vercel.app/
