### ISSUE TITLE
Staking rewards are incorrect

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#33]
This is very important - please let me know if you have questions about this. The rewards should match the tracker.

![Screen Shot 2021-08-16 at 6.55.35 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/377cd1a2-d968-427c-aed2-951139f6d047)

![Screen Shot 2021-08-16 at 6.55.19 PM.png](https://images.zenhubusercontent.com/5f07ce5a8cf129080163e5a4/980795ec-116f-4777-8aff-1adf8fff882b)

**Comment by parrot9design** [comment]
Originally filed here: https://github.com/balancednetwork/balanced-network-info/issues/29
