### ISSUE TITLE
Implement new volume API

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#44]
We have a new API to calculate DEX volume that is more in line with how CMC does it.

@pranav925 please leave it in the comments

**Comment by pranav925** [comment]
The new volumes and fees endpoint is right here: https://balanced.geometry.io/api/v1/stats/dex-pool-stats-24h

Each pool is separate with its pool id and a key. 
Each pool has a `volume` and  `fees` section. 
All token values are in units of their keys (token contract address)

Example format:
```
{
  "0x2": {
    "volume": {
      "cx2609b924e33ef00b648a409245c7ea394c467824": "0x94559603303314a54385",
      "cx88fd7df7ddff82f7cc735c871dc519838cb235bb": "0xe1a40bd56cc32e681b49"
    },
    "fees": {
      "cx2609b924e33ef00b648a409245c7ea394c467824": {
        "lp_fees": "0x38f5db65938859d781",
        "baln_fees": "0x38f5db65938859d781"
      },
      "cx88fd7df7ddff82f7cc735c871dc519838cb235bb": {
        "lp_fees": "0x56a564ccd5cbf93cc5",
        "baln_fees": "0x56a564ccd5cbf93cc5"
      }
    }
  }
}
```
