### ISSUE TITLE
Add more details about Balanced positions

### ISSUE THREAD

**Issue by parrot9design** [balancednetwork/balanced-network-info#51]
We could include another section on the Stats page to display the health of positions on Balanced. 
- Current collateral/LTV ratios (highest, lowest, average for platform)
- Price when the first positions will be liquidated
- Bad debt (if any)
- ? 

This info would help to inform decisions about adjusting the LTV ratio, and will be interesting to monitor in general.

**Comment by BennyOptions** [comment]
Could be worth sending a tweet and asking for community ideas as well
