### ISSUE TITLE
Decimal Place Logic

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#73]
We need to decide how to handle tokens that have a price below 1 cent, as it appears as 0 currently. We should come up with a standard decimal-place logic.

**Comment by gedanziger** [comment]
I think we should just do what crypto exchanges do for price precision  vs trading price (although with less resolution). Tried and true is probably the way to go

**Comment by BennyOptions** [comment]
Yeah sounds good to me - what is the standard logic?

**Comment by parrot9design** [comment]
Can we just use 4 decimal places for every token? We use the same format on the Trade page, it makes sense to keep it consistent.

**Comment by BennyOptions** [comment]
What about when we have assets that have values in the hundreds or thousands?

For example:
- 1,252.5534
- 22,516.1198
- 598.3278

**Comment by parrot9design** [comment]
Hmm, good point. What do you think about this logic? 

If $10 or above: 2 decimals 
If below $10: 4 decimals
If below $0.01: 6 decimals

**Comment by BennyOptions** [comment]
Yeah I'm ok with that. @octocat512 please implement it with the above logic
