### ISSUE TITLE
Display estimated APY included trailing 30 days of fees

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#77]
See the comment below on the governance forum

https://gov.balanced.network/t/improve-apy-display-for-providing-liquidity/379

**Comment by parrot9design** [comment]
Let's add the BALN staking APY to the Stats page:

<img width="1240" alt="Screen Shot 2021-12-24 at 10 45 34 AM" src="https://user-images.githubusercontent.com/63842577/147293979-0fe3b3e2-dfeb-4287-ba69-5f9eab296a4e.png">

- Position the day beside the title
- Change `Fees earned` to `Total fees earned`
- Change the 4th column to BALN staking APY and add this tooltip:

<img width="348" alt="Screen Shot 2021-12-24 at 10 45 45 AM" src="https://user-images.githubusercontent.com/63842577/147294171-51f65ee0-e704-42fa-9871-db715416afbf.png">

APIs required for:
- BALN staking APY
- USD value of network fees from last 30 days

---

Let's also add more detail about the liquidity pool APYs to the Exchange section:

<img width="1222" alt="Screen Shot 2021-12-24 at 10 59 04 AM" src="https://user-images.githubusercontent.com/63842577/147294738-ce173d02-de43-4140-be7b-11237a537023.png">

- All BALN-incentivised pools will show the BALN APY and APY from fees earned by the pool
- All other pools will only show the fee APY

- Add a tooltip to the APY column:
<img width="719" alt="Screen Shot 2021-12-24 at 10 46 11 AM" src="https://user-images.githubusercontent.com/63842577/147294768-df802e70-6760-4648-ac18-46c5ddb76d2b.png">


API required for fee APY

---

You can find the design for this here: http://balanced-development.s3-website-us-east-1.amazonaws.com/stats-dev/
