### ISSUE TITLE
Refactor the stats website by using new data structures from the web app.

### ISSUE THREAD

**Issue by octocat512** [balancednetwork/balanced-network-info#80]
In the stats website code, all tokens-related data are identified/classified by the tokens' symbol. I think it makes frontend code requires frontend devs' development time when adding new token/new pair liquidity data. Using tokens' addresses as a key property is logically correct and it helps scalability for the stats website and reduces adding token/pair time. 

- Import `constants/tokens` and `constants/pairs` files from the web app.
- Use the CurrencyLogo component from the web app instead of using the CurrencyIcon component.
- Refactor all data used tokens' symbol as a key to data structure token address as a key
- Remove tokens' SVG files in this repo. Instead, use the asset repo.

**Comment by BennyOptions** [comment]
@hetfly has plans to refactor when doing the redesign
