### ISSUE TITLE
Protocol Owned Liquidity Display

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-info#93]
We are in the process of building a smart contract for the Balanced DAO Fund to be able to supply liquidity on the Balanced DEX. We should display the liquidity details in the Performance Details section, probably below "Holdings". We essentially need to break up holdings into three categories:

- DAO Fund
- Protocol Owned Liquidity (should look similar to a liquidity details section, where the DAO Fund is the user)

**Comment by parrot9design** [comment]
@BennyOptions you can preview the design here: http://balanced-development.s3-website-us-east-1.amazonaws.com/stats-dev/financial-statements/

**Comment by BennyOptions** [comment]
perfect @parrot9design!

**Comment by BennyOptions** [comment]
blocked by the deployment of the stability fund and POL contracts

**Comment by parrot9design** [comment]
Resolved in https://github.com/balancednetwork/balanced-network-info/pull/134.
